services:
  user-service-postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    image: postgres_custom_ru:latest
    container_name: user-service-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 3
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

#  tt-user-service:
#    build:
#      context: ../../
#      dockerfile: tt-user-service/Dockerfile
#      args:
#        - NO_CACHE=true
#    image: tt-user-service:latest
#    container_name: tt-user-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "9591:9591"
#    networks:
#      - db-net
#    depends_on:
#      task-service-postgres:
#        condition: service_healthy