server:
  port: 9591
spring:
  application:
    name: tt-user-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tt_user_service?minimumIdle=2
    username: tt_user_service_admin
    password: tt_user_service_admin
    hikari:
      minimumIdle: 2
      maximumPoolSize: 4
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
springdoc:
  swagger-ui:
    oauth2-redirect-url: http://localhost:9591/swagger-ui/oauth2-redirect.html
    oauth:
      client-id: swagger-client-user-service
      client-secret: swagger-secret
      use-basic-authentication-with-access-code-grant: true
      scopes: openid,profile,offline_access