services:
  tt-oauth2-authorization-server-postgres:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NO_CACHE=true
    image: postgres_custom_ru:latest
    container_name: oauth2-authorization-server-postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 3
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

#  tt-oauth2-authorization-server:
#    build:
#      context: ../../
#      dockerfile: tt-oauth2-authorization-server/Dockerfile
#      args:
#        - NO_CACHE=true
#    image: tt-oauth2-authorization-server:latest
#    container_name:tt-oauth2-authorization-server
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "9590:9590"
#    networks:
#      - db-net
#    depends_on:
#      tt-oauth2-authorization-server-postgres:
#        condition: service_healthy