server:
  port: 8080
spring:
  application:
    name: tt-task-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tt_task_service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
